/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.UIManager;

public class ConfiguracionInicial extends javax.swing.JFrame {

    int x,y;
    String cityUser;
    String countryUser;

    /**
     *
     */
    public static WindowApp wpInicial;
    
    /**
     * Creates new form ConfiguracionInicial
     */
    public ConfiguracionInicial() {
        initComponents();
        this.setVisible(true);
        
        //Hacemos los JTextField trasnparentes
        insertCity.setBackground(new Color(0,0,0,64));
        insertCountry.setBackground(new Color(0,0,0,64));
        
        //Cambiar icono de la aplicación por el logo que he creado
        setIconImage(new ImageIcon(getClass().getResource("../logo/Logo.png")).getImage());
        
        //Indicamos que la ventana se abra en el medio
        this.setLocationRelativeTo(null);
        
        //Hacemos el fondo transparente
        AWTUtilities.setWindowOpaque(this, false);

        //Más abajo quitamos la ventana con el método "setUndecorated(true);" 
        
        getCityUser();
        getCountryUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        imgPerfil = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        insertCity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        insertCountry = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        accept = new javax.swing.JLabel();
        rombo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User.png"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 180, 150));

        imgPerfil.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        imgPerfil.setForeground(new java.awt.Color(255, 255, 255));
        imgPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPerfil.setText("Seleccionar imagen");
        imgPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgPerfilMouseExited(evt);
            }
        });
        jPanel1.add(imgPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 490, 40));

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/minimizar_BL.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 80, 60));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/cerrar_44.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 70, 50));

        ciudad.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        ciudad.setForeground(new java.awt.Color(255, 255, 255));
        ciudad.setText("Ciudad:");
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        insertCity.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        insertCity.setForeground(new java.awt.Color(255, 255, 255));
        insertCity.setBorder(null);
        jPanel1.add(insertCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 360, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 360, 20));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("País:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        insertCountry.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        insertCountry.setForeground(new java.awt.Color(255, 255, 255));
        insertCountry.setBorder(null);
        jPanel1.add(insertCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 360, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 360, 20));

        accept.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accept.setText("Aceptar");
        accept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acceptMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acceptMouseEntered(evt);
            }
        });
        jPanel1.add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 180, 30));

        rombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacesGraficas/800px-Rombo_1.png"))); // NOI18N
        rombo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                romboMouseDragged(evt);
            }
        });
        rombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                romboMousePressed(evt);
            }
        });
        jPanel1.add(rombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 750));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked

        this.setExtendedState(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    private void imgPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPerfilMouseEntered

        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont=imgPerfil.getFont(); 

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        imgPerfil.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 26));
        
        //Cambio la posición del jlabel
        jPanel1.setLayout(null);
        imgPerfil.setLocation(130, 260);
     
        // TODO add your handling code here:
    }//GEN-LAST:event_imgPerfilMouseEntered

    private void imgPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPerfilMouseExited

        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont=imgPerfil.getFont(); 

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        imgPerfil.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 20));
        // TODO add your handling code here:
    }//GEN-LAST:event_imgPerfilMouseExited

    private void imgPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPerfilMouseClicked

        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Buscar imagen");

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            
            rsscalelabel.RSScaleLabel.setScaleLabel(img, fc.getSelectedFile().toString());
            img.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_imgPerfilMouseClicked

    //Para poder mover la ventana
    private void romboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romboMousePressed
    
        x = evt.getX();
        y = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_romboMousePressed

    //Para poder mover la ventana
    private void romboMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romboMouseDragged
    
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
        // TODO add your handling code here:
    }//GEN-LAST:event_romboMouseDragged

    private void acceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseEntered
   
        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont=accept.getFont(); 

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        accept.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 26));
        
        //Cambio la posición del jlabel
        jPanel1.setLayout(null);
        accept.setLocation(300, 600);
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptMouseEntered

    private void acceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseExited
    
        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont=accept.getFont(); 

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        accept.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 20));
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptMouseExited

    //Creamos un objeto de tipo WindowApp para llamar a la ventana principal del programa y que se abra 
    private void acceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseClicked

        wpInicial = new WindowApp();
        wpInicial.setVisible(true);

        //Cerramos la ventana actual
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptMouseClicked

    public String getCityUser () {
        
        cityUser = insertCity.getText();
        System.out.println(cityUser);
        return cityUser;
    }
    
    public String getCountryUser () {
        
        countryUser = insertCountry.getText();
        return countryUser;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accept;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel ciudad;
    private javax.swing.JLabel img;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JTextField insertCity;
    private javax.swing.JTextField insertCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel rombo;
    // End of variables declaration//GEN-END:variables
}
