/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import com.sun.awt.AWTUtilities;
import javax.swing.ImageIcon;

/**
 * 
 * @author Anabel Jorge
 */
public class Informacion extends javax.swing.JFrame {

    int x,y;
    
    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
        this.setVisible(true);
        
        //Cambiar icono de la aplicación por el logo que he creado
        setIconImage(new ImageIcon(getClass().getResource("../logo/Logo.png")).getImage());
        
        //Indicamos que la ventana se abra en el medio
        this.setLocationRelativeTo(null);
        
        //Hacemos el fondo transparente
        AWTUtilities.setWindowOpaque(this, false);
        
        //Más abajo quitamos la ventana con el método "setUndecorated(true);"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreApp = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        desarrollador = new javax.swing.JLabel();
        nombreDesarrollador = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        curso = new javax.swing.JLabel();
        ManchaInf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreApp.setFont(new java.awt.Font("Courier New", 1, 80)); // NOI18N
        nombreApp.setForeground(new java.awt.Color(255, 255, 255));
        nombreApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreApp.setText("Nakan ");
        jPanel1.add(nombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 340, 60));

        version.setFont(new java.awt.Font("Courier New", 1, 40)); // NOI18N
        version.setForeground(new java.awt.Color(255, 255, 255));
        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("Versión 1.0");
        jPanel1.add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 370, -1));

        desarrollador.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        desarrollador.setForeground(new java.awt.Color(255, 255, 255));
        desarrollador.setText("Desarrollador:");
        jPanel1.add(desarrollador, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        nombreDesarrollador.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        nombreDesarrollador.setForeground(new java.awt.Color(255, 255, 255));
        nombreDesarrollador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreDesarrollador.setText("Anabel Jorge Villanueva");
        jPanel1.add(nombreDesarrollador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 380, -1));

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/minimizar_BL.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 70, 40));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/cerrar_44.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 70, 60));

        curso.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        curso.setForeground(new java.awt.Color(255, 255, 255));
        curso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curso.setText("DAW1");
        jPanel1.add(curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 120, 30));

        ManchaInf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacesGraficas/ManchaI.png"))); // NOI18N
        ManchaInf.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ManchaInfMouseDragged(evt);
            }
        });
        ManchaInf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ManchaInfMousePressed(evt);
            }
        });
        jPanel1.add(ManchaInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 910));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Mover la ventana
    private void ManchaInfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManchaInfMousePressed
  
        x = evt.getX();
        y = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_ManchaInfMousePressed

    //Mover la ventana
    private void ManchaInfMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManchaInfMouseDragged
    
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
        // TODO add your handling code here:
    }//GEN-LAST:event_ManchaInfMouseDragged

    //Minimizar aplicación
    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
    
        this.setExtendedState(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    //Cerrar la ventana y volver a la principal
    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
  
        dispose();
        ConfiguracionInicial.wpInicial.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManchaInf;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel curso;
    private javax.swing.JLabel desarrollador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel nombreApp;
    private javax.swing.JLabel nombreDesarrollador;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
