/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import com.sun.awt.AWTUtilities;
import javax.swing.ImageIcon;

/**
 *
 * @author Anabel Jorge
 */
public class Note extends javax.swing.JFrame {

    /**
     * Creates new form Note
     */
    public Note() {
        initComponents();
    
        //Cambiar icono de la aplicación por el logo que he creado
        setIconImage(new ImageIcon(getClass().getResource("../logo/Logo.png")).getImage());

        //Indicamos que la ventana se abra en el medio
        this.setLocationRelativeTo(null);

        //Hacemos el fondo transparente
        AWTUtilities.setWindowOpaque(this, false);

        //Más abajo quitamos la ventana con el método "setUndecorated(true);"
        
        elegirColor();
    }
    
    public void elegirColor() {
        
        colour.addItem("Color:");
        colour.addItem("Amarillo");
        colour.addItem("Verde");
        colour.addItem("Azul");
        colour.addItem("Rosa");
        colour.addItem("Naranja");
        colour.setSelectedIndex(2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        colour = new javax.swing.JComboBox<>();
        postit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/minimizar_BL.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 70, 60));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/cerrar_44.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 60, 60));

        colour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(colour, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, 20));

        postit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacesGraficas/PostItAmarillo.png"))); // NOI18N
        jPanel1.add(postit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 800));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
   
        this.setExtendedState(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
    
        //Login.wp.setVisible(true);
        ConfiguracionInicial.wpInicial.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrar;
    private javax.swing.JComboBox<String> colour;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel postit;
    // End of variables declaration//GEN-END:variables
}
