/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * Venatana gráfica del registro de usuarios
 *
 * @author Anabel Jorge
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    int x, y;
    public static ConfiguracionInicial config;
    public static String newUser, newPass;

    public Registro() {
        initComponents();
        this.setVisible(true);

        //Hacemos los JTextField trasnparentes
        user.setBackground(new Color(0, 0, 0, 64));
        pass.setBackground(new Color(0, 0, 0, 64));
        name.setBackground(new Color(0, 0, 0, 64));
        passRepeat.setBackground(new Color(0, 0, 0, 64));

        //Cambiar icono de la aplicación por el logo que he creado
        setIconImage(new ImageIcon(getClass().getResource("../logo/Logo.png")).getImage());

        //Indicamos que la ventana se abra en el medio
        this.setLocationRelativeTo(null);

        //Hacemos el fondo transparente
        AWTUtilities.setWindowOpaque(this, false);

        //Más abajo quitamos la ventana con el método "setUndecorated(true);"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registrarse = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        nombre = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        password = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        passwordRepeat = new javax.swing.JLabel();
        passRepeat = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        aceptar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        circulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarse.setFont(new java.awt.Font("Courier New", 1, 52)); // NOI18N
        registrarse.setForeground(new java.awt.Color(255, 255, 255));
        registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarse.setText("Registro");
        registrarse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                registrarseMouseDragged(evt);
            }
        });
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registrarseMousePressed(evt);
            }
        });
        jPanel1.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        usuario.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario:");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        user.setBackground(new java.awt.Color(0, 0, 0));
        user.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setBorder(null);
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 267, 320, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 320, 30));

        nombre.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre:");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 327, 320, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 320, 30));

        password.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Contraseña:");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        pass.setBackground(new java.awt.Color(0, 0, 0));
        pass.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(null);
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 387, 320, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 320, 30));

        passwordRepeat.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        passwordRepeat.setForeground(new java.awt.Color(255, 255, 255));
        passwordRepeat.setText("Contraseña:");
        jPanel1.add(passwordRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        passRepeat.setBackground(new java.awt.Color(0, 0, 0));
        passRepeat.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        passRepeat.setForeground(new java.awt.Color(255, 255, 255));
        passRepeat.setBorder(null);
        jPanel1.add(passRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 447, 320, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 320, 30));

        aceptar.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aceptarMouseExited(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 230, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/linea - copia.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 50, 70));

        cancelar.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarMouseExited(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 310, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/cerrar_44.png"))); // NOI18N
        cerrar.setToolTipText("Cerrar aplicación");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, -1));

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/minimizar_BL.png"))); // NOI18N
        minimizar.setToolTipText("Minimizar aplicación");
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 70, 30));

        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/800px/800px-POMEGRANATE_Logo2.png"))); // NOI18N
        circulo.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        circulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                circuloMouseDragged(evt);
            }
        });
        circulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                circuloMousePressed(evt);
            }
        });
        jPanel1.add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 802, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cerrar aplicación
    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked

        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * Método para poder mover la ventana con el mouse
     *
     * @param evt
     */
    private void registrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMousePressed

        x = evt.getX();
        y = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarseMousePressed

    /**
     * Método para poder mover la ventana con el mouse
     *
     * @param evt
     */
    private void registrarseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarseMouseDragged

    /**
     * Método para poder mover la ventana con el mouse
     *
     * @param evt
     */
    private void circuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_circuloMousePressed

        x = evt.getX();
        y = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_circuloMousePressed

    /**
     * Método para poder mover la ventana con el mouse
     *
     * @param evt
     */
    private void circuloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_circuloMouseDragged

        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
        // TODO add your handling code here:
    }//GEN-LAST:event_circuloMouseDragged

    /**
     * Método que redirige a la ventana de Configuración inicial. También cierra la actual.
     * esta ventana.
     * @param evt
     */
    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked

         /* try {
            connect();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            dbQuerys conection = new dbQuerys();
            
            if (conection.Register()) {*/
                
                config = new ConfiguracionInicial();
                config.setVisible(true);

                //Cerramos la ventana actual
                dispose();
           /* } 
            else {
                
                JOptionPane.showMessageDialog(null, "Error: Usuario incorrecto", "Usuario incorrecto", JOptionPane.WARNING_MESSAGE);
            }
            
            
            //wp = new WindowApp();
            //dispose();
            /*Proyecto.wp = new Thread(new WindowApp());
            Proyecto.wp.start();*/
            //wp.setVisible(true);
            // TODO add your handling code here:
       /* } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        /*config = new ConfiguracionInicial();
        config.setVisible(true);

        //Cerramos la ventana actual
        dispose();*/
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarMouseClicked

   /* public void connect() throws SQLException {
        
        dbQuerys conection = new dbQuerys();
        
        getUserName();
        getPassUser();

        conection.Register();
    }
    
    public String getUserName() {
        
        newUser = user.getText();
        System.out.println(newUser);
        
        return newUser;
    }
    
    public String getPassUser() {
        
        newPass = pass.getText().toString();
        System.out.println(newPass);
        
        return newPass;
    }*/
    
    /**
     * Método que llama a la ventana de Inicio de sesión y cierra la actual.
     *
     * @param evt
     */
    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked

        Login l = new Login();
        l.setVisible(true);

        //Cerramos la ventana actual
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarMouseClicked

    //Minimizar la ventana
    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked

        this.setExtendedState(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizarMouseClicked

    /**
     * Método que se encarga de cambiar el tamaño y posición del texto al pasar
     * el mouse por encima.
     *
     * @param evt
     */
    private void aceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseEntered

        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont = aceptar.getFont();

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        aceptar.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 44));

        //Cambio la posición del jlabel
        jPanel1.setLayout(null);
        aceptar.setLocation(170, 580);

        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarMouseEntered

    /**
     * Método que se encarga de devolver el tamaño y posición del texto al
     * original al quitar el mouse de encima.
     *
     * @param evt
     */
    private void aceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseExited

        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont = aceptar.getFont();

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        aceptar.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 36));

        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarMouseExited

    /**
     * Método que se encarga de cambiar el tamaño y posición del texto al pasar
     * el mouse por encima.
     *
     * @param evt
     */
    private void cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseEntered

        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont = cancelar.getFont();

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        cancelar.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 44));

        //Cambio la posición del jlabel
        jPanel1.setLayout(null);
        cancelar.setLocation(400, 580);

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarMouseEntered

    /**
     * Método que se encarga de devolver el tamaño y posición del texto al
     * original al quitar el mouse de encima.
     *
     * @param evt
     */
    private void cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseExited

        //Recojo la fuente que se esta utilizando actualmente.
        Font auxFont = cancelar.getFont();

        //Aplico la fuente actual, y al final le doy el tamaño del texto...
        cancelar.setFont(new Font(auxFont.getFontName(), auxFont.getStyle(), 36));

        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aceptar;
    private javax.swing.JLabel cancelar;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel circulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nombre;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField passRepeat;
    private javax.swing.JLabel password;
    private javax.swing.JLabel passwordRepeat;
    private javax.swing.JLabel registrarse;
    private javax.swing.JTextField user;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
